env:
  node: true
  es2021: true
  mocha: true
extends: eslint:recommended
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  indent:
  - error
  - 4
  quotes:
  - error
  - single
  space-before-function-paren:
  - error
  - never
  prefer-arrow-callback:
  - 0
  - allowNamedFunctions: true
  func-names:
  - error
  - never
  padded-blocks:
  - error
  - never
  semi:
  - error
  - always
  keyword-spacing:
  - error
  comma-spacing:
  - error
  - before: false
    after: true
  no-use-before-define:
  - error
  - functions: true
    classes: true

